//! MPRIS (Media Player Remote Interfacing Specification) D-Bus server.
//!
//! Exposes Tempo as a standard MPRIS player on the session bus so that
//! every Linux desktop environment / status bar / KDE Connect / phone
//! remote / hardware media-key handler can talk to us with zero
//! per-app configuration. In particular this is what makes the
//! standard `XF86AudioPlay` / `XF86AudioNext` keyboard keys work on
//! Hyprland, KDE, GNOME, Sway etc. without the user wiring anything
//! up — the compositor / DE auto-routes those to the active MPRIS
//! player.
//!
//! ## Threading model
//!
//! The `mpris-server` crate uses zbus's local server, which means the
//! D-Bus connection has to live on the thread that `.build().await`
//! ran on. We park that on a dedicated OS thread driven by
//! `async_io::block_on`. Communication with the GPUI side happens
//! exclusively through two crossbeam channels:
//!
//! - `MprisCommand` (runtime → GPUI): user pressed a media key /
//!   GNOME widget / phone, fire the corresponding action on the
//!   player entity.
//! - `MprisUpdate` (GPUI → runtime): track changed / paused / volume
//!   moved, push a property-change to D-Bus.
//!
//! Neither side ever blocks on the other; both channels are
//! unbounded and message volume is trivially low (one per state
//! change, one per user input).
//!
//! ## Why local (`spawn_local`-style) instead of `Server`?
//!
//! `mpris_server::Server<T>` requires `T: Send + Sync`, which would
//! force us to teach our internal player snapshot type to be Send.
//! With the local executor we can keep the implementation type owned
//! by the runtime thread and just pass plain `Sender<MprisCommand>`
//! clones into the per-action callbacks (they're closures, not
//! interface implementations).

use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::thread;
use std::time::Duration;

use anyhow::Result;
use crossbeam_channel::{Receiver, Sender};
use mpris_server::{Metadata, PlaybackStatus, Player, Time};

/// Commands generated by external MPRIS clients (media keys, GNOME
/// widget, KDE Connect, etc) that should be applied to the in-app
/// player. Drained on the GPUI thread.
#[derive(Clone, Debug)]
pub enum MprisCommand {
    PlayPause,
    Play,
    Pause,
    Stop,
    Next,
    Previous,
    /// Relative seek in microseconds (positive = forward, negative =
    /// backward). MPRIS `Seek` semantics.
    SeekRelative(i64),
    /// Absolute seek in microseconds from the start of the current
    /// track.
    SetPosition(i64),
    /// Volume in [0.0, 1.0].
    SetVolume(f64),
    /// `Raise` method. We translate to "show window".
    Raise,
}

/// Property updates pushed from the GPUI side into the MPRIS server.
/// The runtime thread drains these and calls the corresponding async
/// `set_*` on the `Player` so the change is broadcast on D-Bus.
#[derive(Clone, Debug)]
pub enum MprisUpdate {
    PlaybackStatus(MprisPlaybackStatus),
    /// New now-playing track. `None` clears metadata (no track loaded).
    Metadata(Option<MprisTrackMeta>),
    Volume(f64),
    /// Position in microseconds. Used to fire the `Seeked` D-Bus
    /// signal so consumers know we jumped (versus the position
    /// advancing naturally).
    Seeked(i64),
}

#[derive(Clone, Copy, Debug)]
pub enum MprisPlaybackStatus {
    Playing,
    Paused,
    Stopped,
}

impl From<MprisPlaybackStatus> for PlaybackStatus {
    fn from(value: MprisPlaybackStatus) -> Self {
        match value {
            MprisPlaybackStatus::Playing => PlaybackStatus::Playing,
            MprisPlaybackStatus::Paused => PlaybackStatus::Paused,
            MprisPlaybackStatus::Stopped => PlaybackStatus::Stopped,
        }
    }
}

#[derive(Clone, Debug, Default)]
pub struct MprisTrackMeta {
    pub title: String,
    pub artist: String,
    pub album: String,
    /// Track length in microseconds. `0` means unknown.
    pub length_us: i64,
    /// Optional `file://` or `https://` URL for cover art. None means
    /// "no art available" — clients show a generic icon.
    pub art_url: Option<String>,
    /// Stable id for the current track. MPRIS requires this to be a
    /// D-Bus object path. We synthesize one from the file path's
    /// hash so it changes when the user switches tracks.
    pub trackid: String,
}

/// Owns the MPRIS runtime thread. Drop the service to shut the D-Bus
/// connection down cleanly.
pub struct MprisService {
    running: Arc<AtomicBool>,
    pub update_tx: Sender<MprisUpdate>,
}

impl MprisService {
    /// Boot the MPRIS server. Returns:
    /// - the service handle (kept alive for the lifetime of the app),
    /// - a `MprisCommand` receiver the GPUI side drains to dispatch
    ///   user input that came in via D-Bus.
    ///
    /// On failure (no session bus, name already taken by another
    /// instance, etc) returns `Err`. The caller logs and continues
    /// running without MPRIS.
    pub fn new(bus_suffix: String) -> Result<(Self, Receiver<MprisCommand>)> {
        let running = Arc::new(AtomicBool::new(true));
        let (cmd_tx, cmd_rx) = crossbeam_channel::unbounded::<MprisCommand>();
        let (update_tx, update_rx) = crossbeam_channel::unbounded::<MprisUpdate>();

        let running_clone = running.clone();
        // The dedicated thread name shows up in `ps -T` /
        // `gdb info threads` so the name is worth getting right.
        thread::Builder::new()
            .name("tempo-mpris".into())
            .spawn(move || {
                async_io::block_on(run_mpris_server(
                    bus_suffix,
                    running_clone,
                    cmd_tx,
                    update_rx,
                ));
            })?;

        Ok((Self { running, update_tx }, cmd_rx))
    }

    /// Push an update to D-Bus. Cheap, never blocks.
    pub fn push_update(&self, update: MprisUpdate) {
        let _ = self.update_tx.send(update);
    }
}

impl Drop for MprisService {
    fn drop(&mut self) {
        self.running.store(false, Ordering::Release);
    }
}

/// Runtime entry point. Builds the `Player`, wires per-method
/// callbacks to channel sends, then loops on the update channel
/// while concurrently driving `player.run()`.
async fn run_mpris_server(
    bus_suffix: String,
    running: Arc<AtomicBool>,
    cmd_tx: Sender<MprisCommand>,
    update_rx: Receiver<MprisUpdate>,
) {
    let build_result = Player::builder(&bus_suffix)
        .identity("Tempo")
        // `desktop_entry` is the basename (no `.desktop`) of the
        // .desktop file. Even if we don't ship one yet, populating
        // the field makes media-key routing more reliable.
        .desktop_entry("tempo")
        .can_play(true)
        .can_pause(true)
        .can_go_next(true)
        .can_go_previous(true)
        .can_seek(true)
        .can_control(true)
        .can_raise(true)
        .build()
        .await;
    let player = match build_result {
        Ok(player) => player,
        Err(error) => {
            crate::perf::event("mpris.build_failed", format!("error={error}"));
            return;
        }
    };

    // ---- Wire incoming method calls to channel sends. ----
    // Each callback is a `Fn(&Player)` so it can be cloned freely;
    // we move a `Sender` clone in. Sends are non-blocking (unbounded
    // channel) so D-Bus dispatch latency never spikes.
    {
        let tx = cmd_tx.clone();
        player.connect_play_pause(move |_| {
            let _ = tx.send(MprisCommand::PlayPause);
        });
    }
    {
        let tx = cmd_tx.clone();
        player.connect_play(move |_| {
            let _ = tx.send(MprisCommand::Play);
        });
    }
    {
        let tx = cmd_tx.clone();
        player.connect_pause(move |_| {
            let _ = tx.send(MprisCommand::Pause);
        });
    }
    {
        let tx = cmd_tx.clone();
        player.connect_stop(move |_| {
            let _ = tx.send(MprisCommand::Stop);
        });
    }
    {
        let tx = cmd_tx.clone();
        player.connect_next(move |_| {
            let _ = tx.send(MprisCommand::Next);
        });
    }
    {
        let tx = cmd_tx.clone();
        player.connect_previous(move |_| {
            let _ = tx.send(MprisCommand::Previous);
        });
    }
    {
        let tx = cmd_tx.clone();
        player.connect_seek(move |_, offset| {
            let _ = tx.send(MprisCommand::SeekRelative(offset.as_micros()));
        });
    }
    {
        let tx = cmd_tx.clone();
        player.connect_set_position(move |_, _track_id, position| {
            let _ = tx.send(MprisCommand::SetPosition(position.as_micros()));
        });
    }
    {
        let tx = cmd_tx.clone();
        player.connect_set_volume(move |_, volume| {
            let _ = tx.send(MprisCommand::SetVolume(volume));
        });
    }
    {
        let tx = cmd_tx.clone();
        player.connect_raise(move |_| {
            let _ = tx.send(MprisCommand::Raise);
        });
    }

    crate::perf::event("mpris.server_started", format!("bus={bus_suffix}"));

    // ---- Main loop: drive `player.run()` and the update channel
    // concurrently. ----
    //
    // We can't simply `await player.run()` because then we'd never
    // poll the update channel. We can't put `run()` in a separate
    // task either (the local runtime owns it). So we manually
    // alternate: poll the update channel non-blocking, apply any
    // pending updates, then yield once to let the D-Bus task make
    // progress. The 50ms tick is a reasonable balance between
    // responsiveness (state changes propagate quickly to the
    // taskbar) and CPU usage when nothing is changing.
    use futures_util::FutureExt as _;
    let mut run_task = player.run().fuse();
    while running.load(Ordering::Acquire) {
        // Drain pending updates.
        loop {
            match update_rx.try_recv() {
                Ok(update) => apply_update(&player, update).await,
                Err(crossbeam_channel::TryRecvError::Empty) => break,
                Err(crossbeam_channel::TryRecvError::Disconnected) => return,
            }
        }
        // Yield to the D-Bus task with a short timeout so we wake up
        // periodically to check the update channel. `select!` between
        // the run task and a timer.
        futures_util::select! {
            _ = run_task => {
                // Run task ended (server shut down). Done.
                break;
            }
            _ = async_io::Timer::after(Duration::from_millis(50)).fuse() => {
                // Tick: loop back to drain channel.
            }
        }
    }

    crate::perf::event("mpris.server_exit", "");
}

async fn apply_update(player: &Player, update: MprisUpdate) {
    match update {
        MprisUpdate::PlaybackStatus(status) => {
            if let Err(error) = player.set_playback_status(status.into()).await {
                crate::perf::event("mpris.set_playback_status_failed", format!("error={error}"));
            }
        }
        MprisUpdate::Metadata(track) => {
            let meta = build_metadata(track);
            if let Err(error) = player.set_metadata(meta).await {
                crate::perf::event("mpris.set_metadata_failed", format!("error={error}"));
            }
        }
        MprisUpdate::Volume(v) => {
            if let Err(error) = player.set_volume(v).await {
                crate::perf::event("mpris.set_volume_failed", format!("error={error}"));
            }
        }
        MprisUpdate::Seeked(position_us) => {
            if let Err(error) = player.seeked(Time::from_micros(position_us)).await {
                crate::perf::event("mpris.seeked_failed", format!("error={error}"));
            }
        }
    }
}

fn build_metadata(track: Option<MprisTrackMeta>) -> Metadata {
    let mut builder = Metadata::builder();
    if let Some(t) = track {
        // mpris:trackid must be a valid D-Bus object path. Always
        // start with `/` and contain only `[A-Za-z0-9_/]`. We
        // sanitize the caller's stable id; if they pass something
        // unsuitable the consumer will reject it, so be strict.
        let trackid_path = sanitize_trackid(&t.trackid);
        // sanitize_trackid is guaranteed to return a valid object
        // path; the unwrap_or fallback to NO_TRACK is purely
        // defensive and shouldn't fire.
        let track_id = mpris_server::TrackId::try_from(trackid_path)
            .unwrap_or(mpris_server::TrackId::NO_TRACK);
        builder = builder.trackid(track_id);
        if !t.title.is_empty() {
            builder = builder.title(t.title);
        }
        if !t.artist.is_empty() {
            builder = builder.artist(vec![t.artist]);
        }
        if !t.album.is_empty() {
            builder = builder.album(t.album);
        }
        if t.length_us > 0 {
            builder = builder.length(Time::from_micros(t.length_us));
        }
        if let Some(art) = t.art_url
            && !art.is_empty()
        {
            builder = builder.art_url(art);
        }
    }
    builder.build()
}

/// Force a string into the shape `/A/B/C` where each segment is
/// `[A-Za-z0-9_]+`. Anything else is replaced with `_`. Always
/// prefixes with the canonical `/org/mpris/MediaPlayer2/Tempo/`
/// path so collisions with other apps' track ids are impossible.
fn sanitize_trackid(input: &str) -> String {
    let mut out = String::from("/org/mpris/MediaPlayer2/Tempo/");
    for ch in input.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.ends_with('/') {
        out.push_str("Track");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sanitize_trackid_strips_special_chars() {
        let id = sanitize_trackid("/home/user/Music/Album/Track 01.flac");
        assert!(id.starts_with("/org/mpris/MediaPlayer2/Tempo/"));
        assert!(!id.contains(' '));
        assert!(!id.contains('.'));
    }

    #[test]
    fn sanitize_trackid_empty_appends_track() {
        let id = sanitize_trackid("");
        assert!(id.ends_with("/Track"));
    }

    #[test]
    fn sanitize_trackid_keeps_alphanumerics() {
        let id = sanitize_trackid("abc123");
        assert!(id.ends_with("/abc123"));
    }
}
